#-------------------------------------------------------------------------------
# FOSS Verilog Toolchain
#
# Author:	Rhys Thomas
# Created:	2018-07-17
#-------------------------------------------------------------------------------

# PROJECT METADATA
PROJ	= project
BUILD	= ./build
IMG		= ./img
DEVICE	= 1k

# FILES
FILES	= top.v
TESTS	= top_tb.v

-include ../makefile
